spring:
    application:
        name: profile-service

    r2dbc:
        url: r2dbc:pool:mysql://localhost:3306/${MYSQL_DB:profiledb}
        username: ${MYSQL_USER:mysql}
        password: ${MYSQL_PASSWORD:mysql}

server:
    port: 9214
